Empty URI should be replaced by the default one.
Addressing:
Info: Scap_upload[storage](provider=foreman_proxy): Uploading results to /openscap/arf/untitled/2014-07-19
Error: Upload failed: the scheme http does not accept registry part: :80 (or bad hostname?)
Error: /Stage[main]/Openscap::Xccdf::Foreman_audit/Xccdf_scan[untitled]/ensure: change from absent to present failed: Upload failed: the scheme http does not accept registry part: :80 (or bad hostname?)