Define Puppet.feature.openscap
Addressing:
Debug: Puppet::Type::Xccdf_scan::ProviderOpenscap: feature openscap is missing

Note: Unless you update to the latest Puppet (includes commit b61fa20) you will
still encounter the following error:

    Error: Could not find a suitable provider for xccdf_scan

In which case you are adviced to update your puppet.