Use next instead of break when fact is missing
In Ruby you're supposed to use next to exit a block, otherwise you get
errors like:

    Error: Facter: Error while resolving custom fact fact='rh_certificate', resolution='<anonymous>': break from proc-closure