Remove the results file only when it exists.
Addressing:
Error: Could not set 'present' on ensure: No such file or directory -
/var/lib/openscap/xccdf_scan/untitled/2014-07-19.rds.xml.bz2 at
72:/etc/puppet/environments/production/modules/openscap/manifests/xccdf/foreman_audit.pp
Wrapped exception:
No such file or directory -
/var/lib/openscap/xccdf_scan/untitled/2014-07-19.rds.xml.bz2
Error:
/Stage[main]/Openscap::Xccdf::Foreman_audit/Xccdf_scan[untitled]/ensure:
change from absent to present failed: Could not set 'present' on ensure:
No such file or directory -
/var/lib/openscap/xccdf_scan/untitled/2014-07-19.rds.xml.bz2 at
72:/etc/puppet/environments/production/modules/openscap/manifests/xccdf/foreman_audit.pp