Enable puppet-openscap on older ruby versions (like 1.8)
It now requires ruby-openscap (rubygem-openscap) >= 0.2.0

Addressing:
Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Could not autoload xccdf_scan: Could not autoload
/etc/puppet/environments/production/modules/openscap/lib/puppet/provider/xccdf_scan/openscap.rb:
/etc/puppet/environments/production/modules/openscap/lib/puppet/provider/xccdf_scan/openscap.rb:33:
syntax error, unexpected ':', expecting ')'
        session.export_results(rds_file: _target_location_rds)
                                        ^ at
/etc/puppet/environments/production/modules/openscap/manifests/xccdf/foreman_audit.pp:72
on node fedora20.mydomain
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run